# NumPy

In [1]:
import numpy as np
a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [2]:
a

array([1, 2, 3])

In [3]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c=np.array([[[1,2],[3,4]],[[7,8],[5,6]]])
print(c)

[[[1 2]
  [3 4]]

 [[7 8]
  [5 6]]]


In [5]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [6]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [7]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [8]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [10]:
#re3shape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
# np.ones
np.ones((3,4)) # here use topuls

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
# np.zeros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
# np.random
np.random.random((3,4))
#fast random is class and second random is method

array([[0.39808545, 0.95863907, 0.96471523, 0.38898543],
       [0.70267343, 0.83842118, 0.49447736, 0.72295373],
       [0.36090051, 0.22901301, 0.09040253, 0.9960165 ]])

In [14]:
# np.linspace
np.linspace(-10,10,10) # linearly space
# give defult value is float

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [15]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

* diffferent between two element  is eqall

In [16]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* make 3x3 identity matrix

## Array Attributes

In [17]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(4,3)
a3=np.arange(8).reshape(2,2,2)

In [18]:
a1.ndim
# a2.ndim
# a3.ndim

1

In [19]:
# shaper
a1.shape

(10,)

In [20]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
# size
a3.size

8

In [22]:
print(a2.size)
a2

12


array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [23]:
# item size
a2.itemsize

8

* int32 take 4 byte
* int64 take 8 byte

In [24]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


## Changing dtype

In [25]:
# astype 
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Array Operation

In [26]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [28]:
# Scalar operation

# arithmetic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [29]:
# relational
a2>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [30]:
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [31]:
a2==16

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [32]:
# Vector operation

# arithmetic 
a1 +a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [33]:
a1-a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

## Array function

In [34]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[91., 87., 54.],
       [83., 45., 36.],
       [88., 12., 69.]])

In [35]:
# max / min /sum /prod
np.max(a1)

np.float64(91.0)

In [36]:
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

12.0
565.0
4188519296881920.0


* 0 -> col
* 1 - > row

In [37]:
np.max(a1,axis=1)

array([91., 83., 88.])

In [38]:
np.prod(a1,axis=1)

array([427518., 134460.,  72864.])

In [39]:
# mean/ median / std / var
print(np.mean(a1))
np.mean(a1,axis=1)

62.77777777777778


array([77.33333333, 54.66666667, 56.33333333])

In [40]:
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

69.0
26.15244954653293
683.9506172839506


In [41]:
# trigonometric function
np.sin(a1)

array([[ 0.10598751, -0.82181784, -0.55878905],
       [ 0.96836446,  0.85090352, -0.99177885],
       [ 0.0353983 , -0.53657292, -0.11478481]])

In [42]:
# dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [43]:
# log and exponential
np.log (a1)

array([[4.51085951, 4.46590812, 3.98898405],
       [4.41884061, 3.80666249, 3.58351894],
       [4.47733681, 2.48490665, 4.2341065 ]])

In [44]:
# round / floor / ceil

a4=np.random.random((2,3))
a4

array([[0.98301612, 0.87995605, 0.08525018],
       [0.62944343, 0.47695003, 0.3386011 ]])

In [45]:
print(np.round(a4))
print('😊')
print(np.floor(a4))
print('😊')
print(np.ceil(a4))

[[1. 1. 0.]
 [1. 0. 0.]]
😊
[[0. 0. 0.]
 [0. 0. 0.]]
😊
[[1. 1. 1.]
 [1. 1. 1.]]


## indexing and slicing

In [46]:
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [47]:
print(a1)
a1[3]

[0 1 2 3 4 5 6 7 8 9]


np.int32(3)

In [48]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
a2[1,1]

np.int64(5)

In [50]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [51]:
a3[1,0,1]

np.int64(5)

In [52]:
a3[0,1,0]

np.int64(2)

In [53]:
a3[0,0,0]

np.int64(0)

In [54]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [55]:
a1[2:5]

array([2, 3, 4], dtype=int32)

In [56]:
a1[2:5:2]

array([2, 4], dtype=int32)

In [57]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
a2[0,:]

array([0, 1, 2, 3])

In [59]:
a2[:,2]

array([ 2,  6, 10])

In [60]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [61]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [62]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [63]:
a2[1,::3]

array([4, 7])

In [64]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [65]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [66]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [67]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [68]:
a3[0,1,:]

array([3, 4, 5])

In [69]:
a3[1,:,1]

array([10, 13, 16])

In [70]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [71]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## Iteratintg

In [72]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [73]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [75]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [76]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [77]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [78]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [79]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

In [80]:
# reshape

In [81]:
# transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [82]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [83]:
# ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [84]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [85]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

* if result is show without varable then it is temporary 

## Stacking

In [86]:
# horizontaly stacking
a4=np.arange (12).reshape(3,4)
a5=np.arange (12,24).reshape(3,4)

In [87]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [88]:
# verticaly stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## splitting

In [89]:
# horizontaly stacking
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [91]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [92]:
# verticaly stacking
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]