In [1]:
import numpy as np
a=np.random.randint(1,100,15)
a

array([61, 26, 61, 66, 79, 12, 82, 91, 57, 17, 27,  8, 60, 83, 42],
      dtype=int32)

In [2]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[ 2, 42,  8, 42],
       [27, 30, 62, 97],
       [25, 41, 98, 36],
       [80, 56, 89, 62],
       [89,  1, 22, 13],
       [21, 90, 10,  6]], dtype=int32)

## np.sort
* Return a sorted copy of array
* https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [3]:
# np.sort
np.sort(a)

array([ 8, 12, 17, 26, 27, 42, 57, 60, 61, 61, 66, 79, 82, 83, 91],
      dtype=int32)

In [4]:
np.sort(a)[::-1]

array([91, 83, 82, 79, 66, 61, 61, 60, 57, 42, 27, 26, 17, 12,  8],
      dtype=int32)

* Column-wise using axis=0 and row-wise using axis=1.

In [5]:
np.sort(b,axis=0)

array([[ 2,  1,  8,  6],
       [21, 30, 10, 13],
       [25, 41, 22, 36],
       [27, 42, 62, 42],
       [80, 56, 89, 62],
       [89, 90, 98, 97]], dtype=int32)

## np.append
* Append values to the end of an array
*  https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
# np.append
np.append(a,200)

array([ 61,  26,  61,  66,  79,  12,  82,  91,  57,  17,  27,   8,  60,
        83,  42, 200])

In [7]:
b

array([[ 2, 42,  8, 42],
       [27, 30, 62, 97],
       [25, 41, 98, 36],
       [80, 56, 89, 62],
       [89,  1, 22, 13],
       [21, 90, 10,  6]], dtype=int32)

In [8]:
np.append(b,np.ones((b.shape[0],1)))

array([ 2., 42.,  8., 42., 27., 30., 62., 97., 25., 41., 98., 36., 80.,
       56., 89., 62., 89.,  1., 22., 13., 21., 90., 10.,  6.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [9]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[ 2., 42.,  8., 42.,  1.],
       [27., 30., 62., 97.,  1.],
       [25., 41., 98., 36.,  1.],
       [80., 56., 89., 62.,  1.],
       [89.,  1., 22., 13.,  1.],
       [21., 90., 10.,  6.,  1.]])

## np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [10]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [13]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [14]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

## np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [15]:
# code
a.shape

(15,)

In [16]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [17]:
np.expand_dims(a,axis=1)

array([[61],
       [26],
       [61],
       [66],
       [79],
       [12],
       [82],
       [91],
       [57],
       [17],
       [27],
       [ 8],
       [60],
       [83],
       [42]], dtype=int32)

## np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [18]:
a

array([61, 26, 61, 66, 79, 12, 82, 91, 57, 17, 27,  8, 60, 83, 42],
      dtype=int32)

In [19]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  2,  3,  4,  6,  7,  8, 12, 13]),)

In [20]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  2,  3,  4,  6,  7,  8, 12, 13]),)

In [21]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0, 26,  0,  0,  0, 12,  0,  0,  0, 17, 27,  8,  0,  0, 42],
      dtype=int32)

In [22]:
np.where(a%2 == 0,0,a)

array([61,  0, 61,  0, 79,  0,  0, 91, 57, 17, 27,  0,  0, 83,  0],
      dtype=int32)

## np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [23]:
# code 
a

array([61, 26, 61, 66, 79, 12, 82, 91, 57, 17, 27,  8, 60, 83, 42],
      dtype=int32)

In [24]:
np.argmax(a)

np.int64(7)

In [25]:
b

array([[ 2, 42,  8, 42],
       [27, 30, 62, 97],
       [25, 41, 98, 36],
       [80, 56, 89, 62],
       [89,  1, 22, 13],
       [21, 90, 10,  6]], dtype=int32)

In [26]:
np.argmax(b,axis=0)

array([4, 5, 2, 1])

In [27]:
np.argmax(b,axis=1)

array([1, 3, 2, 2, 0, 1])

In [28]:
# np.argmin
np.argmin(a)

np.int64(11)

## np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [29]:
a

array([61, 26, 61, 66, 79, 12, 82, 91, 57, 17, 27,  8, 60, 83, 42],
      dtype=int32)

In [30]:
np.cumsum(a)

array([ 61,  87, 148, 214, 293, 305, 387, 478, 535, 552, 579, 587, 647,
       730, 772])

In [31]:
b

array([[ 2, 42,  8, 42],
       [27, 30, 62, 97],
       [25, 41, 98, 36],
       [80, 56, 89, 62],
       [89,  1, 22, 13],
       [21, 90, 10,  6]], dtype=int32)

In [32]:
np.cumsum(b)

array([   2,   44,   52,   94,  121,  151,  213,  310,  335,  376,  474,
        510,  590,  646,  735,  797,  886,  887,  909,  922,  943, 1033,
       1043, 1049])

In [33]:
np.cumsum(b,axis=0)

array([[  2,  42,   8,  42],
       [ 29,  72,  70, 139],
       [ 54, 113, 168, 175],
       [134, 169, 257, 237],
       [223, 170, 279, 250],
       [244, 260, 289, 256]])

In [34]:
# np.cumprod
np.cumprod(a)

array([                  61,                 1586,                96746,
                    6385236,            504433644,           6053203728,
               496362705696,       45169006218336,     2574633354445152,
          43768767025567584,  1181756709690324768, -8992690396186953472,
       -4605845633640211456,  5096437955763033088, -7310534742467229696])

## np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [35]:
a

array([61, 26, 61, 66, 79, 12, 82, 91, 57, 17, 27,  8, 60, 83, 42],
      dtype=int32)

In [36]:
np.percentile(a,100)

np.float64(91.0)

In [38]:
np.percentile(a,50)

np.float64(60.0)

## np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [39]:
a

array([61, 26, 61, 66, 79, 12, 82, 91, 57, 17, 27,  8, 60, 83, 42],
      dtype=int32)

In [41]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 2, 0, 1, 1, 4, 1, 2, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [42]:
np.histogram(a,bins=[0,50,100])

(array([6, 9]), array([  0,  50, 100]))

## np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [43]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [44]:
a

array([61, 26, 61, 66, 79, 12, 82, 91, 57, 17, 27,  8, 60, 83, 42],
      dtype=int32)

In [46]:
item=[10,20,30,40,50,60,70,80,90,]

np.isin(a,item)

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False])

In [47]:
a[np.isin(a,item)]

array([60], dtype=int32)

## np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [48]:
a

array([61, 26, 61, 66, 79, 12, 82, 91, 57, 17, 27,  8, 60, 83, 42],
      dtype=int32)

In [49]:
np.flip(a)

array([42, 83, 60,  8, 27, 17, 57, 91, 82, 12, 79, 66, 61, 26, 61],
      dtype=int32)

In [50]:
b

array([[ 2, 42,  8, 42],
       [27, 30, 62, 97],
       [25, 41, 98, 36],
       [80, 56, 89, 62],
       [89,  1, 22, 13],
       [21, 90, 10,  6]], dtype=int32)

In [53]:
np.flip(b) # hear occur both row and columns flip

array([[ 6, 10, 90, 21],
       [13, 22,  1, 89],
       [62, 89, 56, 80],
       [36, 98, 41, 25],
       [97, 62, 30, 27],
       [42,  8, 42,  2]], dtype=int32)

In [55]:
np.flip(b,axis=0) # here occurs only column flip

array([[21, 90, 10,  6],
       [89,  1, 22, 13],
       [80, 56, 89, 62],
       [25, 41, 98, 36],
       [27, 30, 62, 97],
       [ 2, 42,  8, 42]], dtype=int32)

## np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [56]:
a

array([61, 26, 61, 66, 79, 12, 82, 91, 57, 17, 27,  8, 60, 83, 42],
      dtype=int32)

In [57]:
np.put(a,[0,1],[10,11]) # here occur permanent change

In [58]:
a

array([10, 11, 61, 66, 79, 12, 82, 91, 57, 17, 27,  8, 60, 83, 42],
      dtype=int32)

## np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [59]:
a

array([10, 11, 61, 66, 79, 12, 82, 91, 57, 17, 27,  8, 60, 83, 42],
      dtype=int32)

In [61]:
np.delete(a,0) # (list ,index)

array([11, 61, 66, 79, 12, 82, 91, 57, 17, 27,  8, 60, 83, 42],
      dtype=int32)

In [62]:
np.delete(a,[0,2,4])

array([11, 66, 12, 82, 91, 57, 17, 27,  8, 60, 83, 42], dtype=int32)

## Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d


In [63]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [64]:
np.intersect1d(m,n)

array([3, 4, 5])

In [65]:
np.setdiff1d(n,m)

array([6, 7])

In [66]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [67]:
m[np.in1d(m,2)]

C:\Users\Priyansu rout\AppData\Local\Temp\ipykernel_4396\1121211304.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,2)]


array([2])

## np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [68]:
a

array([10, 11, 61, 66, 79, 12, 82, 91, 57, 17, 27,  8, 60, 83, 42],
      dtype=int32)

In [69]:
np.clip(a,a_min=25,a_max=60)

array([25, 25, 60, 60, 60, 25, 60, 60, 57, 25, 27, 25, 60, 60, 42],
      dtype=int32)

the value which is less than 25 it convert into 25 and the value which is greater than 60 it c 